export default {
  modal: "kloudi-modal",
  overlay: "kloudi-modal-overlay",
  header: "kloudi-modal-header",
  container: "kloudi-modal-container",
  content: "kloudi-modal-content",
  containerOpen: "kloudi-modal-containerOpen",
  input: "kloudi-modal-input",
  inputOpen: "kloudi-modal-inputOpen",
  inputFocused: "kloudi-modal-inputFocused",
  spinner: "kloudi-modal-spinner",
  suggestionsContainer: "kloudi-modal-suggestionsContainer",
  suggestionsContainerOpen: "kloudi-modal-suggestionsContainerOpen",
  suggestionsList: "kloudi-modal-suggestionsList",
  suggestion: "kloudi-modal-suggestion",
  suggestionFirst: "kloudi-modal-suggestionFirst",
  suggestionHighlighted: "kloudi-modal-suggestionHighlighted",
  trigger: "kloudi-modal-trigger",
};
