export default {
  modal: "kloudi-inline",
  overlay: "kloudi-inline-overlay",
  header: "kloudi-inline-header",
  container: "kloudi-inline-container",
  content: "kloudi-inline-content",
  containerOpen: "kloudi-inline-containerOpen",
  input: "kloudi-inline-input",
  inputOpen: "kloudi-inline-inputOpen",
  inputFocused: "kloudi-inline-inputFocused",
  spinner: "kloudi-inline-spinner",
  suggestionsContainer: "kloudi-inline-suggestionsContainer",
  suggestionsContainerOpen: "kloudi-inline-suggestionsContainerOpen",
  suggestionsList: "kloudi-inline-suggestionsList",
  suggestion: "kloudi-inline-suggestion",
  suggestionFirst: "kloudi-inline-suggestionFirst",
  suggestionHighlighted: "kloudi-inline-suggestionHighlighted",
  trigger: "kloudi-inline-trigger",
  commandPanelInputLogo: "kloudi-inline-input-logo",
  commandPanelInputWrapper: "kloudi-inline-input-wrapper",
  commandPanelInputWrapperFocused: "kloudi-inline-input-wrapper-focused",
};
