export default {
  modal: 'kloudi-modal',
  overlay: 'kloudi-overlay',
  header: 'kloudi-header',
  container: 'kloudi-container',
  content: 'kloudi-content',
  containerOpen: 'kloudi-containerOpen',
  input: 'kloudi-input',
  inputOpen: 'kloudi-inputOpen',
  inputFocused: 'kloudi-inputFocused',
  spinner: 'kloudi-spinner',
  suggestionsContainer: 'kloudi-suggestionsContainer',
  suggestionsContainerOpen: 'kloudi-suggestionsContainerOpen',
  suggestionsList: 'kloudi-suggestionsList',
  suggestion: 'kloudi-suggestion',
  suggestionFirst: 'kloudi-suggestionFirst',
  suggestionHighlighted: 'kloudi-suggestionHighlighted',
  trigger: 'kloudi-trigger',
};
